service: newsletter-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - s3:GetObject
      Resource: arn:aws:s3::*:*

    - Effect: 'Allow'
      Action:
        - 'logs:*'
      Resource: arn:aws:logs:*:*:*

    - Effect: 'Allow'
      Action:
        - SNS:*
      Resource: '*'

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:ListStreams
        - dynamodb:DescribeStream
      Resource: '*'

    - Effect: Allow
      Action:
        - SQS:*
      Resource: '*'

custom:
  stage: ${opt:stage, opt:s, self:provider.stage}
  region: ${opt:region, self:provider.region}
  prefix: "newsletter-${self:custom.stage}-${self:custom.region}"
  userRegisteredTopic: "${self:custom.prefix}-user-registered"
  usersTable: "${self:custom.prefix}-users"
  csvBucket: "${self:custom.prefix}-users"
  mailerQueue: "${self:custom.prefix}-mailer"
  serverless-offline:
    skipCacheInvalidation: true

functions:
  # ---- Subscription Services ----
  subscribeFromAPI:
    handler: src/handlers/subscription/subscribeFromAPI.handler
    environment:
      userRegisteredTopicArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.userRegisteredTopic}" ] ]  }
    events:
      - http:
          path: users/subscribe
          method: post
          cors: true
          warmup: true

  subscribeFromCSV:
    handler: src/handlers/subscription/subscribeFromCSV.handler
    environment:
      userRegisteredTopicArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.userRegisteredTopic}" ] ]  }
      csvBucket: ${self:custom.csvBucket}
    events:
      - s3:
          bucket: ${self:custom.csvBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  # ---- Database Services ----
  saveUser:
    handler: src/handlers/database/saveUser.handler
    environment:
      usersTable: ${self:custom.usersTable}
    events:
      - sns: ${self:custom.userRegisteredTopic}

# ---- Welcome Email ----
  createWelcomeEmail:
    handler: src/handlers/welcomeEmail/create.handler
    environment:
      queueURL:
        Ref: MailerQueue
    events:
      - stream:
          type: dynamodb
          batchSize: 10
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - UsersDynamoDbTable
              - StreamArn

# ---- Mailer ----
  sendEmail:
    handler: src/handlers/mailer/sendEmail.handler
    environment:
      sendgridAPIKey: ''
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MailerQueue
              - Arn
          batchSize: 10

# ---- AWS Resources ----
resources:
  Resources:
    UsersDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    MailerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.mailerQueue}

    MailerQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: MailerQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - SQS:SendMessage
              Resource: { "Fn::GetAtt": ["MailerQueue","Arn"] }

plugins:
  - serverless-offline
  - serverless-plugin-warmup
